### ISSUE TITLE
Оформить отчёт о текущей успеваемости группы АС-55

### ISSUE THREAD

**Issue by idzm** [brstu/MMIPU-2021#1]
Отчет оформить в виде файла **readme.md** и разместить в каталоге `results/as55/`.

**Comment by PavelFedasiuk** [comment]
### Отчёт об успеваемости группы АС-55 

|№ |  ФИО                              | Задание 0 | Задание 1 | Задание 2 | Задание 3 | Задание 4 |
|--|-----------------------------------|:---------:|:---------:|:---------:|:---------:|:---------:|
|1 | Артысюк Илья Викторович           |           |           |           |           |           |
|2 | Васильев Артём Сергеевич          |           |           |           |           |           |
|3 | Вильчук Артём Александрович       |     +     |           |           |           |           |
|4 | Даркович Даниил Анатольевич       |     +     |           |           |           |           |
|5 | Евсеенко Егор Андреевич           |     +     |           |           |           |           |
|6 | Зинькова Дарья Геннадьевна        |     +     |           |           |           |           |
|7 | Куликовский Александр Михайлоыич  |           |           |           |           |           |
|8 | Кучко Андрей Викторович           |     +     |           |           |           |           |
|9 | Лепешев Вячеслав Ильич            |     +     |           |           |           |           |
|10| Лифенец Егор Владимирович         |     +     |           |           |           |           |
|11| Марзан Артём Варельевич           |     +     |           |           |           |           |
|12| Мартынович Сергей Викторович      |     +     |           |           |           |           |
|13| Назаров Андрей Романович          |     +     |           |           |           |           |
|14| Никитенков Евгений Владимирович   |     +     |           |           |           |           |
|15| Озарчук Никита Витальевич         |     +     |           |           |           |           |
|16| Петров Владимир Иванович          |     +     |           |           |           |           |
|17| Пыжевский Марк Генндьевич         |     +     |           |           |           |           |
|18| Рахлей Алексей Сергеевич          |     +     |           |           |           |           |
|19| Родион евгений Сергеевич          |           |           |           |           |           |
|20| Сенкевич Роман Николаевич         |     +     |           |           |           |           |
|21| Тарасевич Алексей Александрович   |           |           |           |           |           |
|22| Точёный Виталий Анатольевич       |     +     |           |           |           |           |
|23| Федосюк Павел Александрович       |     +     |           |           |           |           |
|24| Хмарик Дарья Андреевна            |     +     |           |           |           |           |
|25| Чернецкий Никита Анатольевич      |     +     |           |           |           |           |
|26| Черноокий Илья Владимирович       |     +     |           |           |           |           |
|27| Шамовский Никита Леонидович       |     +     |           |           |           |           |
